version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

  jetstream:
    image: nats
    command: "-js"
    networks: ["nats"]

networks:
  nats:
    name: nats

# nats box
# docker run --network nats --rm -it natsio/nats-box
# nats sub -s nats://nats:4222 hello &
# nats pub -s "nats://nats-1:4222" hello first
# nats pub -s "nats://nats-2:4222" hello second